### ISSUE TITLE
Write code for parent class of Individuals Module

### ISSUE THREAD

**Issue by arlemoine** [arlemoine/CS340_F_24_char_junkies#1]
Configs must be used in this class from Config.py.
Keep modularity and usability in mind.

Notable functionalities:
- [x] Store needed config constants in a dictionary
- [x] Log messages to log file
- [x] View dataframe tables from imported child class data
- [x] View graphs from imported child class data
- [x] Create simple search functionality for specific data

**Comment by CSmith-6** [comment]
Completed the search function and checked off last box
